### ISSUE TITLE
Osan 2.1 kertauskyselyssä yksi vastausvaihtoehto on väärin

### ISSUE THREAD

**Issue by vvirrank** [rage/python-s20#10]
Osan 2.1 kertauskyselyn kysymyksessä 1 on vastausvaihtoehto "if luku == false:".
Kyselyn tarkistus väittää, että vaihtoehto ei ole Pythonin syntaksin mukainen. Python kuitenkin hyväksyy muuttujien nimet "luku" ja "false", joita voidaan verrata annetulla lauseella.

**Comment by pllk** [comment]
Siinä tarkoitettu tulkinta on, että false olisi väärin kirjoitettu totuusarvo False. Kuitenkin mainitsemasi asia on totta, eikä tehtävä ole tuosta syystä hyvä. Se kannattaa muuttaa kurssissa tulevaisuudessa.
