### ISSUE TITLE
Osa 3, Sisäkkäiset silmukat, esimerkki

### ISSUE THREAD

**Issue by jpeltsi** [rage/python-s20#11]
Muuttujan luku arvoa ei muuteta selitteessä kuvatulla tavalla. Ainakin itselläni koodi on seuraava:

luku = int(input("Anna luku: "))
while luku > 0:
    i = 0
    while i < luku:
        print(f"{i} ", end="")
        i += 1
    print()

**Comment by jpeltsi** [comment]
Tämä on kyseisen osion viimeinen esimerkki, missä tuloste on lukupyramidi. Luku-muuttujaa tulisi vähentää ulommassa silmukassa yhdellä, jotta ohjelma toteutuu?

**Comment by jpeltsi** [comment]
Hei ja kiitos vastauksista!

Huomaan ylläolevan raporttini olleen hieman ylimalkainen, pahoittelut!

Kyseessä on osion viimeinen esimerkki lukupyramidistä. Uskoakseni muuttujaa
luku tulisi pienentää yhdellä ulommassa silmukassa.

Hyvää alkanutta syksyä!
Terveisin Jukka Peltola

ti 15.9.2020 klo 19.26 Antti Laaksonen <notifications@github.com> kirjoitti:

**Comment by pllk** [comment]
Raporttisi oli mainio ja tuo tekemäni commit pyrki korjaamaan virheen. Näyttääkö nyt oikealta?

https://python-s20.mooc.fi/osa-3/3-lisaa-silmukoista

**Comment by jpeltsi** [comment]
Häränsilmä 😅!

Kiitos!

ti 15.9.2020 klo 20.56 Antti Laaksonen <notifications@github.com> kirjoitti:
