### ISSUE TITLE
Osa 3.2 Toinen esiintymä

### ISSUE THREAD

**Issue by riksuliksu** [rage/python-s20#12]
Tehtävänannossa jää hieman epäselväksi, mitä pitää tulostaa, kun ei löydetä yhtään esiintymää.

Jostain syystä tällä tulosteella ei päässyt tehtävästä läpi:
if kohta1 < 0 or kohta2 <0:
    print("Osajono ei esiinny merkkijonossa kahdesti.")
Mutta eriyttämällä kohdat kahdeksi ehtolauseeksi meni läpi, vaikka molempien lopputulos oli ainakin näennäisesti sama.

**Comment by mluukkai** [comment]
Pitäisi nähdä koko koodi jotta voisi selvittää missä syy on

**Comment by riksuliksu** [comment]
`mjono = input("Anna merkkijono: ")
osajono = input("Anna osajono: ")
kohta1 = mjono.find(osajono)
kohta2 = mjono[kohta1+len(osajono):].find(osajono)
if kohta1 < 0:
    print("Osajono ei esiinny merkkijonossa kahdesti.")
elif  kohta2 < 0:
    print("Osajono ei esiinny merkkijonossa kahdesti.")
else:
    esiintyma = kohta1 + len(osajono) + kohta2
    print(f"Osajonon toinen esiintymä on kohdassa {esiintyma}.")`
Alunperin siis if ja elif olivat yhdistettynä or lauseella

**Comment by mluukkai** [comment]
kyllä tämä menee testeistä läpi:

```python
mjono = input("Anna merkkijono: ")
osajono = input("Anna osajono: ")
kohta1 = mjono.find(osajono)
kohta2 = mjono[kohta1+len(osajono):].find(osajono)
if kohta1 < 0 or kohta2 < 0:
    print("Osajono ei esiinny merkkijonossa kahdesti.")
else:
    esiintyma = kohta1 + len(osajono) + kohta2
    print(f"Osajonon toinen esiintymä on kohdassa {esiintyma}.")
```

**Comment by JerppaTee** [comment]
Ideoita miks tällä ei menny läpi?

```
# Kirjoita ratkaisu tähän
a = input("Anna merkkijono: ")
b = input("Anna osajono: ")

c = []
for match in re.finditer(b, a):
    c.append(match.start())
if len(c) >= 2:
    print("Osajonon toinen esiintymä on kohdassa " + str(c[1]) + ".")
else:
    print("Osajono ei esiinny merkkijonossa kahdesti.")
