### ISSUE TITLE
8-13 maksukortti osa 4

### ISSUE THREAD

**Issue by NinaWeiler** [rage/python-s20#127]
Tehtävä ei mene läpi oikealla tulostuksella, esimerkissä näkyy oikeat luvut. TMC:ssä tulee virheilmo: "...pitäisi olla Pekka: Kortilla on rahaa 30.2 euroa", vaikka oikea summa on 35.4 euroa (kuten esimerkissä näkyy). 
Pekka lataa 20e
Pekka syö maukkaassti 20-4.60, saldo = 15.40
Pekka lataa 20e , saldo = 35.4e

**Comment by pllk** [comment]
Voisitko vielä laittaa TMC-linkin lähettämääsi koodiin, jossa käy näin?

**Comment by NinaWeiler** [comment]
Tässä koodi: https://tmc.mooc.fi/paste/6cSpOQbZecY04ixy_tyTVQ

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pllk** [comment]
Virhe johtuu siitä, että koodissasi on kahdesti rivi pekan_kortti.syo_edullisesti eikä pekan_kortti.syo_edullisesti(). Ilman sulkuja funktiota ei kutsuta, minkä vuoksi Pekan kortilta ei vähene rahaa syömisen yhteydessä.
