### ISSUE TITLE
Teht 08-14_sarja

### ISSUE THREAD

**Issue by viipu** [rage/python-s20#144]
3. osion testit valittavat, jos ei ole käyttänyt luokan määrittelyssä attribuutin nimeä "nimi". Osion suoritusesimerkissä tämä attribuutin nimi on toki mainittu. Konstruktori kuitenkin määritellään jo tehtävän ekassa osiossa. On aika nihkeää puuttua tällä tavalla luokan sisäiseen toteutukseen kertomatta vaatimuksista luokan määrittelyn yhteydessä.

**Comment by pllk** [comment]
Olet ihan oikeassa, ei ole reilua vaatia tuota attribuutin nimeä kertomatta asiasta. Valitettavasti tehtävää ei ole mahdollista muuttaa suuremmin tässä vaiheessa mutta laitoin maininnan tehtävänantoon.
