### ISSUE TITLE
Tehtävä 11-12: tehtävänanto ja testit ristiriidassa

### ISSUE THREAD

**Issue by ljleppan** [rage/python-s20#153]
Tehtävänanto on konfliktissa testien ja mallivastauksen kanssa. Tehtävänanto sanoo "Sanan kirjainten koolla ei ole merkitystä." mutta testien tulokset saa vain jos sanan kirjankoon ottaa huomioon kun laskee esiintymiä. 

Olisi myös tosi hyvä sanoa tehtäväannossa eksplisiittisesti että mitä välimerkeille kuten pisteet ja pilkut pitää tehdä

**Comment by pllk** [comment]
Hyviä huomioita, nyt tehtävänannon pitäisi olla selkeämpi
