### ISSUE TITLE
osa-4/2-lisaa-funktioista, tehtävä neliö, tekstivirhe

### ISSUE THREAD

**Issue by saragilbert** [rage/python-s20#17]
Funktio tulostaa neliön **jonka korkeus ja leveys korkeuden ja leveyden kertoo ensimmäinen parametri.** 

Pitäisi kaiketi olla Funktio tulostaa neliön, jonka korkeuden ja leveyden kertoo ensimmäinen parametri?

**Comment by mluukkai** [comment]
Niimpä... korjattu!
