### ISSUE TITLE
10-7 testit eivät testaa > ja != operaattoreiden olemassaoloa

### ISSUE THREAD

**Issue by mluukkai** [rage/python-s20#172]
![image](https://user-images.githubusercontent.com/523235/98481701-bfeb1400-2204-11eb-9697-51bb2012a361.png)

https://tmc.mooc.fi/paste/iLX51lsmoeEZrTzV9AEEnQ riitti 5/5

**Comment by pllk** [comment]
Ilmeisesti testissä ei ole vikaa vaan ei haittaa jos noita ei jaksa toteuttaa...
