### ISSUE TITLE
Osa 10: perintä opetusmateriaaliin jäänyt esimerkkeihin this-termi

### ISSUE THREAD

**Issue by terhik** [rage/python-s20#178]
Olisiko Java-kurssilta jäänyt this - selfin sijaan?
--
Opettaja- ja Opiskelija-luokilla voisi olla yhteinen yliluokka Henkilo:

class Henkilo:

   def __init__(self, nimi: str, sposti: str):
       **this.nimi = nimi
       this.sposti = sposti**
Luokassa on toteutettu siis henkilöön liittyvät piirteet. Nyt luoka Opiskelija ja Opettaja voivat periä luokan ja lisätä perittyjen ominaisuuksien rinnalle uusia piirteitä:

Perintä tapahtuu kirjoittamalla luokan nimen perään perittävän luokan nimi sulkuihin:

class Henkilo:

   def __init__(self, nimi: str, sposti: str):
       **this.nimi = nimi
       this.sposti = sposti**

**Comment by pllk** [comment]
Kiitos havainnosta, tämä korjataan. Tosiaan varmaankin syynä on tottuminen Javan syntaksiin.
