### ISSUE TITLE
10-11 Luokka mäsänä

### ISSUE THREAD

**Issue by sippe2** [rage/python-s20#179]
Pitäisi olla ehkä näin:

<img width="414" alt="Näyttökuva 2020-11-9 kello 21 41 16" src="https://user-images.githubusercontent.com/31264116/98588444-60f4d000-22d4-11eb-8c80-4a8fa458302a.png">

**Comment by pllk** [comment]
Miten se on nyt?

**Comment by sippe2** [comment]
No kun en muista, kun en tajunnut tallettaa sitä ennen aloittamista, mutta ongelma sisennyksissä.

**Comment by pllk** [comment]
OK, korjasin sen ehkä. VS Code jotenkin bugittaa niin en pääse testaamaan tällä hetkellä
