### ISSUE TITLE
teht 12-04: test_7_vaikeuden_mukaan_toimii_1

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#190]
![image](https://user-images.githubusercontent.com/25852159/98965626-eebdfe80-2512-11eb-91b9-61fb88466035.png)

Esimerkissä nouseva järjestys, testissä laskeva:

![image](https://user-images.githubusercontent.com/25852159/98965716-0b5a3680-2513-11eb-9e73-9405eb876436.png)

**Comment by mluukkai** [comment]
fixd
