### ISSUE TITLE
teht 12-12: test_13_kurssin_suorittajat_toimii_1

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#199]
samat tyypit, eri järjestys. 
Pitäisi hyväksyä, koska tehtävänannossa ei mainita mitään järjestämisestä

![image](https://user-images.githubusercontent.com/25852159/98997650-7b7db200-253d-11eb-9e41-3745e475604c.png)

**Comment by sippe2** [comment]
Sortedin jälkeen testi on sitä mieltä, että kolme henkilöä pitäisi löytyä listalta, mutta todellisuus taitaa olla kaksi.

<img width="531" alt="Näyttökuva 2020-11-15 kello 20 38 04" src="https://user-images.githubusercontent.com/31264116/99193624-f2f05300-2782-11eb-89d9-c58450b9f1bf.png">

**Comment by sippe2** [comment]
Testit menevät näköjään läpi, kun lobotoi arvonsanan tarkistuksen.

**Comment by mluukkai** [comment]
joo, vireitä oli, nyt parempi <3
