### ISSUE TITLE
1.4 Jatketaanko -tehtävän tarkistusvirhe

### ISSUE THREAD

**Issue by jpeltsi** [rage/python-s20#2]
koodissa silmukan sisässä

    vastaus = input("moi\nJatketaanko? ")

Tuloste on ajettaessa aivan oikein, mutta tarkistus lähetyksen jälkeen antaa virheilmoituksen. Sen mukaan ohjelma tulostaa vain yhden rivin 3 rivin sijaan. Ilmeisesti tarkistus ei ymmärrä input-parametrin sisällä olevaa \n:ää rivinvaihdoksi.

**Comment by mluukkai** [comment]
joo, näin ei teknisten rajoitteiden vuoksi voi tehdä
