### ISSUE TITLE
teht 12-14: voisi olla vielä yksi testi....

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#208]
.... testaamaan ettei tyhjällä merkkijonolla tule True, kun pitäisi tulla False

**print(kaikki_vokaaleja(""))**   tuottaa testikoodillani True ja sain jo täydet pisteet tehtävästä, vaikka
testien olisi pitänyt ottaa mielestäni tämä tilanne kiinni.

eli funktiossa pitäisi olla kommentoidut rivit, jotta saisi täydet pisteet:

def kaikki_vokaaleja(merkkijono: str):
    #if merkkijono == "":
    #    return False
    lauseke = re.compile("[aeiouyäöå]")  
    for merkki in  merkkijono:
         if not lauseke.search(merkki):
            return False
    return True

**Comment by pllk** [comment]
Jos merkkijono on tyhjä, niin se täyttää vaatimuksen "kaikki merkit ovat vokaaleja"...
