### ISSUE TITLE
12-13 Tehtävänanto luvallakin sanoen haastava

### ISSUE THREAD

**Issue by sippe2** [rage/python-s20#216]
Tehtävää voisi kuvailla erittäin vaikeaksi tai hyvin vaikeaksi. Opiskelijan täytyy kaivaa tietoa netistä ja ymmärtää varsin syvällisesti kokonaisuuden täyttääkseen tehtävänannon vaatimat kriteerit. Materiaali on tämän tehtävän osalta puutteellinen eikä anna tarvittavia työkaluja tehtävän ratkaisuun ja lopputulos näyttää sekavalle. Kokemus lähinnä latistava, sillä tehtävän voi ratkaista huomattavasti helpommin aikaisemmin opituilla menetelmillä ja reducea hyödyntäen.

**Comment by mluukkai** [comment]
Joo, tuolla luentomateriaalilla tehtävä on käytännössä mahoton. Parannellaan luennon reduce-selvitystä. Saa olla aika fakiiri jos pystyy _pelkästään_ sen perusteella tekemään tekemään reducella mitään
