### ISSUE TITLE
Osa 11,  sivu 2, Yleisimmät sanat -tehtävässä kirj.virhe

### ISSUE THREAD

**Issue by Handeriina** [rage/python-s20#217]
Esimerkkitulostuksessa on virhe? 
Jos noudattaa tehtävänantoa, niin sen pitäisi olla:
{'list': 6, 'comprehension': 4, 'is': 3, 'and': 3, 'for': 3, 'in': 3}
Tekstissä esiintyy ”list” 4 kertaa ja ”List” 2 kertaa, niin eikö niiden pitäisi siis olla sama avain sanakirjassa ja kasvattaa samaa arvoa eli yhteensä niitä olisi 6 (eikä 4)?

**Comment by pllk** [comment]
Tässä on ollut epäyhtenäisyyttä tehtävänannossa ja testeissä. Nyt tehtävänanto vastaa testejä eli pieniä ja suuria kirjaimia käsitellään eri tavalla (toisin kuin tehtävänanto ohjeisti aiemmin).
