### ISSUE TITLE
Lottorivi, osa 2 Kirjoita luokkaan metodi osumat_paikoillaan(pelattu_rivi)

### ISSUE THREAD

**Issue by saragilbert** [rage/python-s20#221]
Funktion nimi ja ohjeteksti saattaa hieman johtaa harhaan, osumienhan ei tarvitse olla _paikallaan_ vaan olemassa.

**Comment by sanelisai** [comment]
Selkeytyisi vähän enemmän jo siitä, että todettaisiin "listassa on _vanhoilla_ paikoillaan oikeat numerot"

**Comment by pllk** [comment]
Hyvä ehdotus @sanelisai - laitoin nyt tämän muotoilun
