### ISSUE TITLE
12-06 Tehtävänanto epäselvä ja vaikea ymmärtää

### ISSUE THREAD

**Issue by sippe2** [rage/python-s20#224]
Voisiko tehtävää helpottaa esimerkiksi funktioiden käyttöesimerkillä, jotka täytyy keksiä nyt itse? Esim:

<img width="527" alt="Näyttökuva 2020-11-18 kello 2 54 38" src="https://user-images.githubusercontent.com/31264116/99468615-9e4b0480-2949-11eb-9759-41fd6f396801.png">

Tulostuksen pitäisi näyttää tältä:
Kelju Kojootti
('Uka Naakka', 9)
Palloilija(nimi=Hessu Hopo, pelinumero=4, maalit=3, syotot=9, minuutit=12)

Samoin voisiko tehtävän viimeisen osan laittaa ensimmäiseksi, sillä se on helpoin toteuttaa? 

Tämä oli oikeasti aika haastavaa keksiä annetun materiaalin pohjalta:
max(alko, key=lambda viinipullo: viinipullo.hinta)**.lempinimi**

**Comment by mluukkai** [comment]
hyvä pointti se vikan siirto alkuun

tuohan pitäs olla sikäli "helppo" ymmärtää, että 

```
viinapullo_olio = max(alko, key=lambda viinipullo: viinipullo.hinta)
```

eli max ottaa yhden olion sieltä listasta

ja sille oliolle sitten voidaan kutsua metodeja tai kaivaa attribuutteja normaaliin tapaan

```
viinapullo_olio.lempinimi
```

idea on aikalailla sama kun esim tässä tehtävässä https://python-s20.now.sh/osa-9/1-oliot-ja-viittaukset#programming-exercise-nopein-auto

**Comment by mluukkai** [comment]
mutta tuo "melkein sama tehtävä" on jo monen viikon takaa...

**Comment by sippe2** [comment]
No nyt kun mainitsit, niin etäinen haju, että vastaavanlainen olisi ollut joskus... En vain yksinkertaisesti osannut yhdistää näitä kahta asiaa. :D
