### ISSUE TITLE
Osa 5-6: sudokutarkistimen testissä virhe

### ISSUE THREAD

**Issue by taavi-fck** [rage/python-s20#24]
Testin mukaan seuraavan sudokun

sudoku = [
  [ 0, 2, 3, 4, 5, 6, 7, 8, 9 ],
  [ 0, 0, 0, 0, 1, 3, 5, 6, 9 ],
  [ 0, 0, 0, 1, 3, 5, 6, 8, 9 ],
  [ 0, 1, 2, 3, 4, 5, 6, 8, 9 ],
  [ 0, 0, 0, 1, 2, 5, 6, 7, 8 ],
  [ 0, 0, 0, 2, 3, 4, 5, 6, 7 ],
  [ 0, 0, 0, 2, 3, 4, 5, 6, 7 ],
  [ 0, 0, 0, 0, 2, 3, 5, 7, 8 ],
  [ 0, 0, 0, 1, 3, 4, 5, 7, 9 ],]

arvo pitäisi olla True, vaikka sen sarakkeet ovat selvästi väärin. Esimerkiksi viimeisessä sarakkeessa on peräti viisi (5) yhdeksikköä.

**Comment by pllk** [comment]
Voisitko laittaa linkin TMC-palautukseen, jossa tämä ongelma ilmenee?

**Comment by taavi-fck** [comment]
Miten?

**Comment by pllk** [comment]
Lähettämällä koodin TMC:hen ja hakemalla sivulta https://tmc.mooc.fi/ linkin koodiin, jossa ilmenee testaajan virheellinen toiminta

**Comment by taavi-fck** [comment]
https://tmc.mooc.fi/submissions/8593481#files

**Comment by pllk** [comment]
Kiitos, tuossa oli ongelmana että koodisi muutti parametrina annettua sudokua ja testin virheilmoituksessa näkyi sitten se muutettu sudoku eikä alkuperäinen. Nyt tämä virhe testin virheilmoituksessa on korjattu.
