### ISSUE TITLE
teht 12-06 osapisteet (1 tai 2 pistettä)

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#242]
Tehtävästä voi saada 3 pistettä, luulisi että joka osasta saa yhden pisteen.
Kuitenkin seuraava koodi on 0 pistettä Submit Solutionissa

https://tmc.mooc.fi/paste/s4cqn5qjahV-wUB3VrRcoA

Myös testien nimet ovat hämmentäviä, kaikki alkavat sanalla PisteidenMukaanTest
vaikka pitäisi testata 3 eri asiaa, siis maaleja, pisteitä ja minuutteja.

Kannattanee testata myös muut osapisteet.

**Comment by pllk** [comment]
Nyt koetin korjata nämä ongelmat
