### ISSUE TITLE
pygame - scancode

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#243]
Minun Windows-koneessa on eri koodit kuin tässä esimerkissä. 

![image](https://user-images.githubusercontent.com/25852159/99911863-c2b73000-2cff-11eb-9b02-00d05419fe17.png)

Minulla tuli scancodet:
YLÖS = 72
OIKEALLE = 77
ALAS = 80
VASEMMALLE = 75

https://python-s20.now.sh/osa-13/3-tapahtumat

**Comment by pllk** [comment]
Kiitos tiedosta, tämä on tärkeä tieto. Kuvittelin että tavallisissa näppäimissä scancodet olisivat samoja eri koneissa.

**Comment by niinasaarelainen** [comment]
Tuli mieleen pari lisätestiä aiheeseen liittyen:

1) Testasin onko sillä väliä, onko Keyboard Setting FI vai EN(United States). Yritin käynnistää pygame-koodia näppäimistön EN-asetuksellä, mutta VSC väkisin vaihtoi EN--> FI ohjelman suorituksen alussa (saman väkisinvaihdoksen teki toinen editorini IDLE), joten en pääse testaamaan englanti-asetuksella

2) näppäinkoodit, jotka sivulla  https://python-s20.now.sh/osa-13/3-tapahtumat  mainitaan (275 ja 276) 
lienevät samoja. Minulla tuli (Windows 7 Professional, keyboard: FI )
YLÖS = 273
OIKEALLE = 275
ALAS = 274
VASEMMALLE = 276

**Comment by pllk** [comment]
Kohtaan 2: näin arvelin mutta jostain syystä ne vaikuttivat eroavan kotikoneellani ja työkoneellani (tai sitten mokasin jotain), minkä takia vaihdoin scancodeihin

**Comment by pllk** [comment]
Ilmeisesti kyse on siitä että näppäinkoodit eroavat Pygamen versioissa 1 ja 2. Eli jos käyttää Pygamen vakioita eikä numerokoodeja niin pitäisi toimia.
