### ISSUE TITLE
12-4-tehtävä, pikkuvirhe testissä

### ISSUE THREAD

**Issue by Handeriina** [rage/python-s20#246]
Kiipeilyreitti-tehtävän testi KiipeilyreittiTest: test_8_vaikeuden_mukaan_toimii_2
Pikku puute rivillä 
vastaus = vaikeuden_mukaan([r1, r2)
Pitäisikö olla näin:
vastaus = vaikeuden_mukaan([r1, r2, r3])
<img width="569" alt="Näyttökuva 2020-11-24 kello 11 55 46" src="https://user-images.githubusercontent.com/64781521/100078879-ad9be780-2e4c-11eb-8cf7-93b534b84858.png">

**Comment by pllk** [comment]
Kiitos havainnosta, nyt tämä korjattu
