### ISSUE TITLE
Opintopisteet osat 1-3

### ISSUE THREAD

**Issue by saragilbert** [rage/python-s20#250]
Esimerkkikoodeissa pitäisi olla mukana print, jos puhutaan esimerkkitulosteesta,  copypasteilijat kuten allekirjoittanut, hämmentyvät kun esimerkkikoodi ei toimikaan kuten esitetty :)

    summa = kaikkien_opintopisteiden_summa([s1, s2, s3])
    **print(summa)**

**Comment by pllk** [comment]
Ihan totta, ilman muuta koodien tulee antaa ilmoitettu tuloste
