### ISSUE TITLE
Virheellinen linkki 

### ISSUE THREAD

**Issue by platipus82** [rage/python-s20#252]
Linkki https://python-s20.mooc.fi/osa-12/osa-6/1-tiedostojen-lukeminen#programming-exercise-kurssin-tulokset-osa-3 on virheellinen - oikea lienee https://python-s20.mooc.fi/osa-6/1-tiedostojen-lukeminen#programming-exercise-kurssin-tulokset-osa-3

**Comment by viipu** [comment]
Kannattaa kertoa vähän tarkemmin mistä virhe löytyy: esim osion nimi (tässä tapauksessa: Sivu 12-4) tai linkki sivulle (tässä tapauksessa: https://python-s20.mooc.fi/osa-12/4-saannolliset-lausekkeet) jossa virhe on. 

Taustaa miksi just tässä tapauksessa issuen speksaus hämmensi: materiaalissa käytetään suhteellisia tiedostopolkuja (eli url:n domain jää pois, ja viitataan suhteessa hakemistorakenteeseen ihan samoin kuin tavallisissa kansioissa), joten tarkalleen tuon muotoista linkkiä ei reposta edes löydy. Muutenkin vähän tarkempi speksaus auttaa paljon virheen löytämisessä :)
