### ISSUE TITLE
11-07 lottorivi virheilmo

### ISSUE THREAD

**Issue by viipu** [rage/python-s20#254]
virheellinen metodikutsun selitys virheilmossa, virheellinen rivi korostettu

 : Metodin osumat_paikoillaan pitäisi palauttaa
[1, -1, 5, -1, 9, -1, 11]
kun sitä kutsutaan seuraavasti:
rivi = Lottorivi([1, 3, 5, 7, 9, 11, 13])
**n = rivi.osumien_maara([1, 2, 5, 6, 9, 10, 11])**
nyt metodi palauttaa
[1, -1, 5, -1, 9, 11, -1]

![image](https://user-images.githubusercontent.com/1564285/100391026-e7cadc00-303a-11eb-9c20-a094b59a3737.png)

**Comment by pllk** [comment]
Kiitos, tämä on nyt korjattu
