### ISSUE TITLE
12 säännölliset lausekkeet

### ISSUE THREAD

**Issue by mluukkai** [rage/python-s20#258]
malliratkaisussa on myös käytetty re.compile, jota en löytänyt meidän materiaalista mutta tutorialissa sanotaan, että se tekee ehdon käyttämisestä tehokkaampaa. Onko tämä sellainen asia, joka on ns. itsestään selvyys, jota jatkossa tulee aina käyttää? Vaikka koodi toimisi ilmankin?

testit myös aika liberaalit, hyväksyvät esim seuraavan

``` 

def kellonaika(merkkijono: str):
  kellonaika = ("[0-2][0-3]:[0-5][0-9]:[0-5][0-9]")
  if re.search(kellonaika, merkkijono):
      return True
   else:
      return False
  
```

**Comment by pllk** [comment]
Nyt ei ole compilea ratkaisuissa. Korjasikohan joku testejä, en pystynyt toistamaan tuota ongelmaa.
