### ISSUE TITLE
11-13 testit 

### ISSUE THREAD

**Issue by viipu** [rage/python-s20#263]
Pitäisi testata myös tilannetta, jossa listassa on valmiiksi oikea määrä alkioita. Nyt ratkaisu, jossa lisätään alkio ensin, ja tarkistetaan pituus vasta sitten, johtaa vähän hämmentävään virheviestiin rekursiivisuudesta:

![image](https://user-images.githubusercontent.com/1564285/101020521-4c27f700-3577-11eb-9aa4-f36dbc077457.png)

Onko muuten jokin erityinen syy miksi halutaan vaatia rekursiivista kutsua myös tapauksessa, jossa tulee lisätä vain yksi alkio? Alkion lisäämisen ja rekursion kutsumisenhan voisi laittaa omiin if-lohkoihinsa, kuten alla. Tämä kuitenkin johtaa taas samaan virheviestiin.
Tälle voi siis olla ihan syy, mutta sen suuntaan voisi siinä tapauksessa materiaalissakin viitata. Tällaisenaan virheviesti ei auta oikean ratkaisun suuntaan, koska viesti on edelleen sama, joka se on myös esim. while-rakenteella toteutetussa ratkaisussa.

![image](https://user-images.githubusercontent.com/1564285/101021449-9a89c580-3578-11eb-897d-23a510ce976b.png)

**Comment by pllk** [comment]
Parantelin testejä tämän perusteella. Nyt rekursion käyttöä testataan listalla [1,2], jossa voi luontevasti olettaa että tapahtuu rekursiota.
