### ISSUE TITLE
osa 14: Sokoban: muuttujien nimeäminen, luokat

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#264]
useita issueita, kun olen päässyt koodinluvussa seuraavaan asti:

**if self.kartta[uusi_y][uusi_x] in [3, 5]:
            kolmas_y = uusi_y + dy
            kolmas_x = uusi_x + dx**

1) please, ei muuttujan nimeä kolmas_y. vaan joku asiaa kuvaavampi sana.
    Onko kyse laatikon_y:stä vai jostain muusta? Pitkäkin muuttujan nimi on parempi kuin kolmas_y
2) dy. Mistä d on lyhenne, en heti keksi
3) [3, 5] tiedän että nuo selitettiin alussa, mutta miksei voisi lukea "laatikko", "laatikko_valmis" . (Muunnos numeroiksi tehtäisiin sanakirjalla.)  Tajuaisi heti mistä on kyse.
4) toive: jos kerran lähdettiin tekemään luokkia, miksei käytetä luokkia Robotti ja Laatikko

**Comment by pllk** [comment]
Tein sen yhden luokan Matin lepyttämiseksi, mutta rajansa kaikella että olisi useampia luokkia

**Comment by pllk** [comment]
Kohtia 1 ja 2 on nyt parannettu. Aiemmissa nimissä kirjain d tuli sanasta delta (eli muutos).

**Comment by pllk** [comment]
Kohdasta 3 kerrotaan vähän myöhemmin materiaalissa kohdassa "Refaktorointia?"
