### ISSUE TITLE
osa 14: Loppukyselyt, 2 bugia

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#266]
sivulla lukee: Loppukysely, osa 3
pitäisi olla:  osa 14

Tältä näyttää koko kurssin loppukysely:
![image](https://user-images.githubusercontent.com/25852159/101413021-3ce4d880-38ec-11eb-938f-8c3f0908ea02.png)

**Comment by pllk** [comment]
Ilmeisesti nämä ovat korjaantuneet jossain vaiheessa
