### ISSUE TITLE
Osa 13 pygame-tehtävät; malliratkaisusta voi kopioida jos ei ihan osaa tehtävää

### ISSUE THREAD

**Issue by viipu** [rage/python-s20#268]
Tehtävistä kun saa automaagisesti pisteet vaikka koodi olisi mitä, pääsee malliratkaisun katsomaan vaikka tehtävää ei varsinaisesti tekisi. Voisiko malliratkaisut tässä tapauksessa julkaista vasta kierroksen sulkeuduttua?

Toisaalta on yhtäkkiä vähän kohtuutonta odottaa, että opiskelija palauttaisi kunkin tehtävän vain kerran, kun aiemmilla viikoilla on totuttu muuhun. Jos siis vaikka huomaa jälkikäteen tehneensä jonkin hölmön virheen, ei tällä yhden palautuksen mentaliteetilla voisi korjata virheitään (tai ainakaan olla varma, että korjauksesta ei rankaista).

**Comment by pllk** [comment]
Nämä ovat hyviä kommentteja ja viikon 13 toteutuksessa on selkeästi parannettavaa tulevaisuudessa. Malliratkaisujen julkaisu vasta viikon jälkeen voisi poistaa monta ongelmaa, myös sen että vahingossa lähettää vastauksen liian aikaisin ja silloinkin saa nähtäväksi malliratkaisun. Toisaalta joskus olisi hyvä että näkisi viikon aikana jonkin tehtävän malliratkaisun.
