### ISSUE TITLE
Tentissä huijausmahdollisuus

### ISSUE THREAD

**Issue by saarasalme** [rage/python-s20#270]
Hei! Huomasin palautettuani tehtävät tentissä OHJA PYTHON, syksy 2020, Tentti 1 että, jos tehtävän palautuksen avaa TestMyCodessa, voi sieltä avata tehtäviin malliratkaisut. En aijo avata muiden tehtävien malliratkaisuja enkä muokannut vastauksiani tämän nähtyäni mutta malliratkaisujen näkeminen on varmaan muillekkin mahdollista.

**Comment by pllk** [comment]
Kiitos ilmoituksesta, hyvä että kerroit ja tutkimme asiaa

**Comment by pllk** [comment]
Tosiaan oli vahingossa jäänyt testikoodia sinne, nyt sen pitäisi olla poissa

**Comment by saarasalme** [comment]
Mahtavaa! Ei näy itselle enää.
