### ISSUE TITLE
Tehtävän 6_14 testit kenkkuilevat (ainakin paikallisesti)

### ISSUE THREAD

**Issue by viipu** [rage/python-s20#37]
Jos tiedostoon kirjoituksen tekee pääohjelmassa, mutta ei tee sitä `with`-lohkolla, tehtävän `osa06-14_kurssin_tulokset_osa4` testien tarkistuksissa jää (ainakin minulla) kummittelemaan edellisen testin tuloksena syntyneet tiedostot `tulos.txt` ja `tulos.csv`. Eli testit eivät mene läpi, koska vertaushetkellä tiedostoissa on aina edellisen testin tulostukset. Kun suoritusta kokeilee itse samoilla syötteillä, tiedostojen tekstit ovat suorituksen jälkeen oikein. 

Asia korjaantui sulkemalla tiedostot koodissa. Tästä voisi olla maininta tehtävänannossa; materiaalissa ei tähän kohtaan mennessä ole puhuttu tiedostojen sulkemisesta kuin (automaationa) lohkojen suorituksen päättyessä sekä (ohjelmoijan toteuttamana) tiedostojen tyhjentämisen yhteydessä. Tiedostojen tila ennen niiden sulkemista/sulkeutumista jää muutenkin materiaalissa epäselväksi.

**Comment by pllk** [comment]
Materiaalissa pitäisi olla käytäntönä, että tiedostoja käsitellään with-lohkossa, jolloin tiedosto sulkeutuu automaattisesti. Ihan totta kyllä että tulevaisuudessa tätä asiaa olisi hyvä parantaa ja kertoa tarkemmin sulkemisesta ja close-metodista.
