### ISSUE TITLE
Tehtävä 08_08: funktion nimi eri testissä ja tehtävänannossa

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#42]
TMC: Ohjelmastasi pitäisi löytyä funktio nimeltä vanhempi_kirja

![image](https://user-images.githubusercontent.com/25852159/96297883-417ec600-0ffa-11eb-9f0f-333192b2891d.png)

**Comment by sippe2** [comment]
Kirjoittaja ja kirjan nimi väärin päin.

<img width="844" alt="Näyttökuva 2020-10-18 kello 3 55 11" src="https://user-images.githubusercontent.com/31264116/96356385-1f6a6e00-10f6-11eb-8f5c-182f42a9740a.png">
