### ISSUE TITLE
Tehtävä 08_02: Pysyy punaisena onnistuneesta palautuksesta huolimatta.

### ISSUE THREAD

**Issue by sippe2** [rage/python-s20#43]
Oppimateriaalin puolella tehtävän onnistunut suorittaminen ei muuta tehtävän palautuksen statusta.

**Comment by pllk** [comment]
Esiintyykö tämä ongelma vielä? Testasin ja itselläni ratkaistu tehtävä 8.2 näkyy vihreänä oppimateriaalissa.
