### ISSUE TITLE
Kertaus 2.1 vaatii osan 2.3 tuntemusta

### ISSUE THREAD

**Issue by TamarixGallica** [rage/python-s20#5]
Kertaus 2.1:ssä ensimmäisessä tehtävässä kysytään mitkä vaihtoehdoista ovat Pythonin syntaksin mukaisia. Vaihtoehtojen joukossa on `if a == 30 and b == 14:`. Ehtojen yhdistäminen kuitenkin esitellään vasta osassa 2.3, joten tässä vaiheessa kurssia käyvällä ei välttämättä tiedä yhdistetäänkö ehdot Pythonissa `and`:lla, `&&`:lla vai jollakin muulla vaihtoehdolla.

**Comment by TamarixGallica** [comment]
Vaihtoehdoissa on näköjään toinenkin vaihtoehto, joka vaatii 2.3:n tuntemusta ennen vastaamista.

**Comment by mluukkai** [comment]
korjataan keväälle
