### ISSUE TITLE
teht 08-13_maksukortti  negatiivinen arvo?

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#51]
https://tmc.mooc.fi/paste/k-GpeUB1bnH9yYwOwj9wHQ

![image](https://user-images.githubusercontent.com/25852159/96335045-150c8d80-107e-11eb-9a77-1257efb21ec8.png)

epäinformatiivinen virheilmoitus: en tiedä mitä pitäisi korjata.
Tosin omasta mielestäni koodi nostaa ValueError;in negatiivisella arvolla, kuten pitääkin
tehtävänannon mukaan.

Eli onko virhe koodissa vai TMC-testissä?

**Comment by sippe2** [comment]
Tässä omat huomioni. Anteeksi tuplaissue:

Testit menevät läpi kommentoimalla ValueErrorin pois koodista.
https://github.com/rage/python-s20/issues/58
