### ISSUE TITLE
None mallivastauksissa ennen kuin asia on opetettu

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#54]
täällä on mallivastauksessa **None** (osa 8, eka tehtävä):
https://tmc.mooc.fi/exercises/108747/solution

kuitenkin se tulee kurssimateriaalissa vastaan osassa 9:
https://python-s20.now.sh/osa-9/2-oliot-attribuuttina

**Comment by pllk** [comment]
Kiitos ilmoituksesta, nyt on uusi malliratkaisu ilman Nonea
