### ISSUE TITLE
Tehtävä 08-13: Kattosumman tarkistus puuttuu, ValueError rikki ja mallivastaus puutteellinen

### ISSUE THREAD

**Issue by sippe2** [rage/python-s20#58]
<img width="819" alt="Näyttökuva 2020-10-19 kello 2 24 56" src="https://user-images.githubusercontent.com/31264116/96388852-6028bc80-11b4-11eb-96cf-c7cb07d9a582.png">

<img width="833" alt="Näyttökuva 2020-10-19 kello 2 32 40" src="https://user-images.githubusercontent.com/31264116/96388859-69198e00-11b4-11eb-9d54-616dbe9ce451.png">

**Mallivastauksen ValueError-osio puuttuu kokonaan.**

**Comment by mluukkai** [comment]
fided
