### ISSUE TITLE
osa07-10_henkilotunnus_oikein testit eivät testaa liian pitkän hetun huomioimista

### ISSUE THREAD

**Issue by viipu** [rage/python-s20#67]
7.henkilotunnus_oikein testit eivät testaa, onko huolehdittu ettei hetu ole liian pitkä.

Cf. https://tmc.mooc.fi/submissions/8725958#files
testitulostus tuottaa True, vaikka ei pitäisi; koodi menee kuitenkin läpi testeistä sekä lokaalisti että palvelimella.

**Comment by pllk** [comment]
Kiitos, lisätään tällainen testi
