### ISSUE TITLE
Ohjelmointitehtävä: Toinen esiintymä mallivastausvirhe?

### ISSUE THREAD

**Issue by jpeltsi** [rage/python-s20#8]
Mallivastaus ei toteuttanut tehtävän asettelun päällekkäisyysvaatimusta, kun sen ajoi pythontutor:ssa.

**Comment by pllk** [comment]
Kiitos ilmoituksesta, malliratkaisu oli tosiaan virheellinen. Nyt sen pitäisi olla korjattu.
