### ISSUE TITLE
teht 09-15  MatkalaukkuTest: test3_tyhja_matkalaukku_repr  väärin

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#80]
![image](https://user-images.githubusercontent.com/25852159/96993834-83e15f00-1534-11eb-8edf-66231ba38b69.png)

vs. 

![image](https://user-images.githubusercontent.com/25852159/96994012-bbe8a200-1534-11eb-895c-da54bbe597f1.png)

**Comment by sippe2** [comment]
Tehtävä ei näytä valmiilta...

https://tmc.mooc.fi/paste/ojgzem978YifnhWjm9fKDg

**Comment by pllk** [comment]
Nyt on ehkä valmiimpi
