### ISSUE TITLE
teht 09-06 punainen (=väärä status www:ssä)

### ISSUE THREAD

**Issue by niinasaarelainen** [rage/python-s20#81]
![image](https://user-images.githubusercontent.com/25852159/96994654-afb11480-1535-11eb-9432-91fc05d83c07.png)

sivulla https://python-s20.now.sh/osa-9/2-oliot-attribuuttina
Lemmikit-tehtävä on tehty onnistuneesti, mutta ei ole vihreä
On Refreshattu

Voisiko virhe johtua siitä, että www:ssä tehtävän nimi on **Lemmikit**
ja @TMC se on **9.lemmikki**

**Comment by sippe2** [comment]
Sama huomio.

**Comment by pllk** [comment]
Tämä on ilmeisesti korjautunut jossain välissä
