### ISSUE TITLE
Osa 7 / 15: Tehtävän tarkistuksen virheilmoitukset viittaavat edelliseen tehtävään

### ISSUE THREAD

**Issue by TamarixGallica** [rage/python-s20#82]
Osan 7 tehtävän 15 (Kuka huijasi, osa 2) tarkistuksen virheilmoitukset viittaavat edellisessä tehtävässä totutettuun funktioon. Esim. seuraavan koodi tarkistuttaminen antaa väärän virheilmoituksen:

```
def viralliset_pisteet() -> list:
    pass
```

Virheilmoitus on ```Funktion huijarit tulisi palauttaa sanakirja, nyt se palauttaa arvon None joka on tyyppiä NoneType```. Virheilmoituksen pitäisi viitata funktioon ```viralliset_pisteet```.

**Comment by pllk** [comment]
Kiitos, korjataan tämä
