### ISSUE TITLE
Teht. 09-04: Vikoja tehtävänannossa

### ISSUE THREAD

**Issue by sippe2** [rage/python-s20#85]
OSA 1:
https://tmc.mooc.fi/paste/P-Yjeor6l-9J1S2UqCNQIg

<img width="813" alt="Näyttökuva 2020-10-24 kello 4 36 53" src="https://user-images.githubusercontent.com/31264116/97066387-b71c0080-15bd-11eb-93ac-f5125e18bddf.png">

OSA 3
https://tmc.mooc.fi/paste/o3mCZ07xVKV5n0BHKSqyQg

<img width="819" alt="Näyttökuva 2020-10-24 kello 6 02 18" src="https://user-images.githubusercontent.com/31264116/97066621-7d4bf980-15bf-11eb-9543-63e58e6c21ee.png">

OSA 4
Testit menee läpi, mutta pääohjelma väärin:

<img width="812" alt="Näyttökuva 2020-10-24 kello 6 12 01" src="https://user-images.githubusercontent.com/31264116/97066760-9dc88380-15c0-11eb-9d45-bafa3202ffa0.png">

**Comment by pllk** [comment]
Viimeinen luku on kai kuitenkin 1100 eikä 1104.3?
